server:
  port: 80
  servlet:
    session:
      timeout: 30

spring:
  servlet:
    multipart:
      max-file-size: 100MB #单个文件大小
      max-request-size: 100MB #总上传文件大小
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/myshop?serverTimezone=UTC
      username: root
      password: root
      max-active: 100  #最大连接数
      initial-size: 1  #初始化连接数
      max-wait: 60000  #获取最大等待时间
      min-idle: 1 #最小连接数
      validation-query: select 'x'  #
      time-between-eviction-runs-millis: 60000   #一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000     #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      pool-prepared-statements: false            #是否缓存preparedStatement 在mysql的环境下建议关闭 因为对数据库性能消耗大
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall   #配置监控统计拦截的filters，去掉后监控界面SQL无法进行统计，'wall'用于防火墙

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml #扫描mapper的xml文件
  type-aliases-package: cn.mail.shop.entity  #配置entity类别名，为类首字母小写

file:
  upload:
    path: F:\photos\
  baseUrl: http://127.0.0.1:8080/demo/
